apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: barakmalinski/node-app:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 3000
