//go to lesson of docker in order run images based on node
pipeline {
    agent {
      docker {image 'node:24.17.0-alpine3.24'}
           }
    stages {
        stage ('Test') {
            steps {
                echo 'Testing..'
            }
        }
    }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
        stage('Security') {
            steps {
                echo 'Security....this is the end of course yehhhhhhhhh'
            }
        }
   }


